# Generated by Django 5.2.9 on 2026-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (₹)'),
        ),
    ]
