from datetime import date
from calendar import month_name

from django.db.models import Sum
from django.http import HttpResponse

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from openpyxl import Workbook
from openpyxl.styles import (
    Font,
    PatternFill,
    Border,
    Side,
    Alignment,
)

from rest_framework.views import APIView, Response
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.authentication import JWTAuthentication

from expenses.models import ExpenseModel, BudgetModel

from openpyxl.chart import PieChart, Reference, BarChart
from openpyxl.utils import get_column_letter
class PDFReportAPIView(APIView):

    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

    def add_footer(self, canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 9)
        canvas.setFillColor(colors.grey)
        canvas.drawString(40, 20, "Generated by SmartSpend AI")
        canvas.drawRightString(560, 20, f"Page {doc.page}")
        canvas.restoreState()

    def get(self, request):
        today = date.today()
        month = int(request.query_params.get("month", today.month))
        year = int(request.query_params.get("year", today.year))

        if month < 1 or month > 12:
            return Response(
                {"error": "Invalid month"},
                status=400,
            )

        month_display = f"{month_name[month]} {year}"

        expenses = ExpenseModel.objects.filter(
            user=request.user,
            date__month=month,
            date__year=year,
        ).order_by("date")

        budget = BudgetModel.objects.filter(
            user=request.user,
            month=month,
            year=year,
        ).first()

        total_spent = (
            expenses.aggregate(total=Sum("amount"))["total"] or 0
        )
        budget_amount = budget.budget if budget else 0
        remaining = budget_amount - total_spent

        response = HttpResponse(content_type="application/pdf")
        response["Content-Disposition"] = (
            f'attachment; filename="Expense_Report_{month}_{year}.pdf"'
        )

        document = SimpleDocTemplate(
            response,
            rightMargin=35,
            leftMargin=35,
            topMargin=40,
            bottomMargin=40,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "TitleStyle",
            parent=styles["Title"],
            alignment=TA_CENTER,
            fontSize=24,
            textColor=colors.HexColor("#2563EB"),
            spaceAfter=10,
        )

        heading_style = ParagraphStyle(
            "HeadingStyle",
            parent=styles["Heading2"],
            textColor=colors.HexColor("#1D4ED8"),
            spaceAfter=10,
        )

        normal_style = styles["BodyText"]
        elements = []

        # ==========================================================
        # COMPANY HEADER
        # ==========================================================
        elements.append(Paragraph("<b>SmartSpend AI</b>", title_style))
        elements.append(Paragraph("AI Powered Personal Finance Report", heading_style))
        elements.append(Spacer(1, 15))

        # ==========================================================
        # REPORT INFORMATION
        # ==========================================================
        info_data = [
            ["Report Month", month_display],
            ["Generated For", request.user.username],
            ["Generated On", today.strftime("%d %B %Y")],
        ]

        info_table = Table(info_data, colWidths=[140, 320])
        info_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#2563EB")),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
                    ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        elements.append(info_table)
        elements.append(Spacer(1, 22))

        # ==========================================================
        # FINANCIAL SUMMARY
        # ==========================================================
        elements.append(Paragraph("<b>Financial Summary</b>", heading_style))
        elements.append(Spacer(1, 10))

        summary_data = [
            ["Budget", f"₹ {budget_amount:,.2f}"],
            ["Total Spent", f"₹ {total_spent:,.2f}"],
            ["Remaining", f"₹ {remaining:,.2f}"],
        ]

        summary_table = Table(summary_data, colWidths=[220, 180])
        summary_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EFF6FF")),
                    ("GRID", (0, 0), (-1, -1), 0.75, colors.HexColor("#BFDBFE")),
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1E3A8A")),
                    ("TEXTCOLOR", (1, 0), (1, -1), colors.black),
                    ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                    ("TOPPADDING", (0, 0), (-1, -1), 10),
                    ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#F8FAFC")),
                    ("BACKGROUND", (0, 2), (-1, 2), colors.HexColor("#ECFDF5")),
                ]
            )
        )
        elements.append(summary_table)
        elements.append(Spacer(1, 25))

        # ==========================================================
        # EXPENSE DETAILS TITLE
        # ==========================================================
        elements.append(Paragraph("<b>Expense Details</b>", heading_style))
        elements.append(Spacer(1, 10))

        # ==========================================================
        # EXPENSE TABLE
        # ==========================================================
        table_data = [["Date", "Item", "Category", "Amount"]]

        for expense in expenses:
            table_data.append(
                [
                    expense.date.strftime("%d-%m-%Y"),
                    expense.item,
                    expense.category,
                    f"₹ {expense.amount:,.2f}",
                ]
            )

        expense_table = Table(table_data, colWidths=[90, 180, 110, 90])
        expense_table.setStyle(
            TableStyle(
                [
                    # Header
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 11),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                    ("TOPPADDING", (0, 0), (-1, 0), 10),
                    # Body
                    ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CBD5E1")),
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 1), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
                    ("TOPPADDING", (0, 1), (-1, -1), 8),
                    ("ALIGN", (3, 1), (3, -1), "RIGHT"),
                    ("TEXTCOLOR", (3, 1), (3, -1), colors.HexColor("#15803D")),
                    ("FONTNAME", (3, 1), (3, -1), "Helvetica-Bold"),
                ]
            )
        )

        # Alternate row colors
        for row in range(1, len(table_data)):
            if row % 2 == 0:
                expense_table.setStyle(
                    TableStyle([("BACKGROUND", (0, row), (-1, row), colors.HexColor("#F8FAFC"))])
                )

        elements.append(expense_table)
        elements.append(Spacer(1, 20))
        document.build(
            elements,
            onFirstPage=self.add_footer,
            onLaterPages=self.add_footer,
            )

        return response

class ExcelReportAPIView(APIView):

    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request):

        today = date.today()

        month = int(request.query_params.get("month", today.month))
        year = int(request.query_params.get("year", today.year))

        if month < 1 or month > 12:
            return Response(
                {"error": "Invalid month"},
                status=400,
            )

        month_display = f"{month_name[month]} {year}"

        expenses = ExpenseModel.objects.filter(
            user=request.user,
            date__month=month,
            date__year=year,
        ).order_by("date")

        budget = BudgetModel.objects.filter(
            user=request.user,
            month=month,
            year=year,
        ).first()

        total_spent = (
            expenses.aggregate(
                total=Sum("amount")
            )["total"] or 0
        )

        budget_amount = budget.budget if budget else 0

        remaining = budget_amount - total_spent

        workbook = Workbook()
        sheet = workbook.active
        sheet.title = f"{month_name[month]} Report"

        # ==================================================
        # COLORS
        # ==================================================

        PRIMARY = "2563EB"
        PRIMARY_DARK = "1E3A8A"
        LIGHT = "F8FAFC"
        LIGHT_BLUE = "DBEAFE"
        SUCCESS = "DCFCE7"

        header_fill = PatternFill(
            fill_type="solid",
            fgColor=PRIMARY,
        )

        blue_fill = PatternFill(
            fill_type="solid",
            fgColor=LIGHT_BLUE,
        )

        green_fill = PatternFill(
            fill_type="solid",
            fgColor=SUCCESS,
        )

        thin = Side(
            style="thin",
            color="CBD5E1",
        )

        border = Border(
            left=thin,
            right=thin,
            top=thin,
            bottom=thin,
        )

        center = Alignment(
            horizontal="center",
            vertical="center",
        )

        left = Alignment(
            horizontal="left",
            vertical="center",
        )

        right = Alignment(
            horizontal="right",
            vertical="center",
        )

        # ==================================================
        # TITLE
        # ==================================================

        sheet.merge_cells("A1:F1")
        cell = sheet["A1"]
        cell.value = "SmartSpend AI"
        cell.font = Font(
            size=22,
            bold=True,
            color="FFFFFF",
        )
        cell.fill = header_fill
        cell.alignment = center

        sheet.merge_cells("A2:F2")
        cell = sheet["A2"]
        cell.value = "AI Powered Personal Finance Report"
        cell.font = Font(
            size=14,
            bold=True,
        )
        cell.alignment = center

        sheet["A4"] = "Generated For"
        sheet["B4"] = request.user.username

        sheet["D4"] = "Report Month"
        sheet["E4"] = month_display

        sheet["A5"] = "Generated On"
        sheet["B5"] = today.strftime("%d %B %Y")

        for c in ["A4", "D4", "A5"]:
            sheet[c].font = Font(bold=True)

        sheet.merge_cells("A7:F7")
        cell = sheet["A7"]
        cell.value = "Financial Summary"
        cell.font = Font(
            size=14,
            bold=True,
            color="FFFFFF",
        )
        cell.fill = header_fill
        cell.alignment = center

        # ==================================================
        # SUMMARY CARDS
        # ==================================================

        labels = [
            ("Budget", budget_amount, blue_fill),
            ("Total Spent", total_spent, blue_fill),
            ("Remaining", remaining, green_fill),
        ]

        start_row = 9

        for i, (title, value, fill) in enumerate(labels):
            row = start_row + (i * 2)

            title_cell = sheet.cell(row=row, column=1)
            value_cell = sheet.cell(row=row, column=2)

            title_cell.value = title
            value_cell.value = float(value)

            title_cell.font = Font(
                bold=True,
                size=12,
                color="1E3A8A",
            )

            value_cell.font = Font(
                bold=True,
                size=13,
            )

            title_cell.fill = fill
            value_cell.fill = fill

            title_cell.border = border
            value_cell.border = border

            title_cell.alignment = left
            value_cell.alignment = right

            value_cell.number_format = '₹#,##0.00'

        # ==================================================
        # TABLE HEADER
        # ==================================================

        headers = [
            "Date",
            "Item",
            "Category",
            "Amount",
            "Notes",
            "Recurring",
        ]

        table_row = 17

        for col, header in enumerate(headers, start=1):

            cell = sheet.cell(
                row=table_row,
                column=col,
            )

            cell.value = header

            cell.font = Font(
                bold=True,
                color="FFFFFF",
            )

            cell.fill = header_fill

            cell.border = border

            cell.alignment = center

        # ==================================================
        # EXPENSE DATA
        # ==================================================

        row = table_row + 1

        alternate = PatternFill(
            fill_type="solid",
            fgColor="F8FAFC",
        )

        for expense in expenses:

            sheet.cell(row=row, column=1).value = expense.date.strftime("%d-%m-%Y")
            sheet.cell(row=row, column=2).value = expense.item
            sheet.cell(row=row, column=3).value = expense.category

            amount = sheet.cell(row=row, column=4)
            amount.value = float(expense.amount)
            amount.number_format = '#,##0.00'

            sheet.cell(row=row, column=5).value = expense.notes or ""

            sheet.cell(row=row, column=6).value = (
                "Yes"
                if expense.is_recurring
                else "No"
            )

            for c in range(1, 7):

                cell = sheet.cell(
                    row=row,
                    column=c,
                )

                cell.border = border

                if row % 2 == 0:
                    cell.fill = alternate

                if c == 4:
                    cell.alignment = right
                elif c == 6:
                    cell.alignment = center
                else:
                    cell.alignment = left

            row += 1

        # ==================================================
        # COLUMN WIDTH
        # ==================================================

        sheet.column_dimensions["A"].width = 15
        sheet.column_dimensions["B"].width = 30
        sheet.column_dimensions["C"].width = 22
        sheet.column_dimensions["D"].width = 18
        sheet.column_dimensions["E"].width = 35
        sheet.column_dimensions["F"].width = 15

        # ==================================================
        # FREEZE HEADER
        # ==================================================

        sheet.freeze_panes = "A18"

        # ==================================================
        # FILTER
        # ==================================================

        sheet.auto_filter.ref = f"A17:F{row-1}"

        # ==================================================
        # RESPONSE
        # ==================================================

        response = HttpResponse(
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )

        response[
            "Content-Disposition"
        ] = (
            f'attachment; filename="Expense_Report_{month}_{year}.xlsx"'
        )

        workbook.save(response)

        return response